name: Secret Scan (TruffleHog)

on:
  push:
    branches:
      - dev
      - main
  pull_request:

jobs:
  trufflehog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # important for full history scan

      - name: Run TruffleHog
        uses: trufflesecurity/trufflehog@main
        with:
          path: .
          base: HEAD~1
          head: HEAD
